### ISSUE TITLE
Update frequency.

### ISSUE THREAD

**Issue by dimkagithub** [pujux/badge-it#44]
Hi!
Nice job! )
How often do Gists, Repos and Commits badges  update?
I have 13 Gists, 13 Repos and more than 100 Commits, but badges show 12 Gists, 12 Repos and 85 Commits always.

**Comment by jieunyoo** [comment]
Hi - yes I am also having this issue. The number of repo badges does not seem to update.

**Comment by nitianabhigyan** [comment]
If this is due to a caching issue on Github's side (usually occurs when cache policy is not specified in the resource) please try: 

> Hi, this maybe useful.
SO after reading through : https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache
There is an option to PURGE the images from GitHub cache and FORCE reload. i.e.
curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....

For anyone facing this, please give it a shot.
You can find out the url to purge by right clicking on the image -> open in a new tab -> copy the url

**Comment by pujux** [comment]
The Cache-Control header returned by shields.io is `max-age=86400, s-maxage=86400`
